//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erpv1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class cari
    {
        public int id { get; set; }
        public string Firma_Adi { get; set; }
        public string Yetkili_Ad_Soyad { get; set; }
        public string Vergi_No { get; set; }
        public string Vergi_Dairesi { get; set; }
        public string Adres { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public string Semt { get; set; }
        public string Telefon { get; set; }
        public string mail { get; set; }
    }
}
