//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erpv1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class depolar
    {
        public int id { get; set; }
        public string urunAdi { get; set; }
        public string DepoAdi { get; set; }
        public Nullable<decimal> Miktar { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<decimal> Tutar { get; set; }
    }
}
