//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erpv1.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class erpEntities : DbContext
    {
        public erpEntities()
            : base("name=erpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<depolar> depolar { get; set; }
        public virtual DbSet<DepoTanimlari> DepoTanimlari { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<cari> cari { get; set; }
        public virtual DbSet<numarator> numarator { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<SipDag> SipDag { get; set; }
    }
}
