//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erpv1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.SipDag = new HashSet<SipDag>();
        }
    
        public int ID { get; set; }
        public string SIP_NO { get; set; }
        public string ORDER_NO { get; set; }
        public string RPT_NO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string MAL_TANIMI { get; set; }
        public string PAZARLAMACI { get; set; }
        public string FIRMA_KODU { get; set; }
        public string FIRMA_ADI { get; set; }
        public string ILGILI { get; set; }
        public string DEPARTMAN { get; set; }
        public string TELEFON { get; set; }
        public string ADRES { get; set; }
        public string ULKE { get; set; }
        public string KOMISYONCU { get; set; }
        public string ACIKLAMA { get; set; }
        public string DOKUMA_DETAY { get; set; }
        public string BOYA_DETAY { get; set; }
        public string BASKI_DETAY { get; set; }
        public string KONF_DETAY { get; set; }
        public string NAKIS_DETAY { get; set; }
        public string AKS_DETAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SipDag> SipDag { get; set; }
    }
}
