//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erpv1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SipDag
    {
        public int ID { get; set; }
        public Nullable<int> REF_NO { get; set; }
        public string SIP_REF_NO { get; set; }
        public Nullable<System.DateTime> TERMIN { get; set; }
        public string ART_NO { get; set; }
        public string CINSI { get; set; }
        public string MODEL { get; set; }
        public string KALIP_NO { get; set; }
        public string KUMAS_KODU { get; set; }
        public string KUMAS_ADI { get; set; }
        public string BORDUR_KODU { get; set; }
        public string BORDUR_ADI { get; set; }
        public string EBAT_BEDEN { get; set; }
        public string EN { get; set; }
        public string NOY { get; set; }
        public string GM2 { get; set; }
        public string VARYANT_KODU { get; set; }
        public string VARYANT_ADI { get; set; }
        public string RENK_NO { get; set; }
        public string RENK_ADI { get; set; }
        public string BASKI_KODU { get; set; }
        public string BASKI_ADI { get; set; }
        public string NAKIS_KODU { get; set; }
        public string NAKIS_ADI { get; set; }
    
        public virtual Siparis Siparis { get; set; }
    }
}
